version: '3.8'

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: modula_postgres
    environment:
      POSTGRES_USER: modula_u
      POSTGRES_PASSWORD: root#root
      POSTGRES_DB: modula_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/Users/home/Documents/Code/Go/modulacms/volumes

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: modula_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root#root
      MYSQL_DATABASE: modula_db
      MYSQL_USER: modula_u
      MYSQL_PASSWORD: modula#
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/Users/home/Documents/Code/Go/modulacms/volumes

volumes:
  pgdata:
  mysqldata:

